server:
  port: 8080
  servlet:
    context-path: /school

spring:
  application:
    name: school
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: liu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
